version: '3.8'

services:
  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.2.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    ports:
      - "9042:9042"   # CQL (ScyllaDB Query Language) Port
      - "10000:10000" # Scylla REST API
    networks:
      - web

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:5.2.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    ports:
      - "9043:9042"
      - "10001:10000"
    networks:
      - web

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:5.2.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --reactor-backend=epoll
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    ports:
      - "9044:9042"
      - "10002:10000"
    networks:
      - web

networks:
  web:
    driver: bridge
